### ISSUE TITLE
Replace Strings class with inline strings

### ISSUE THREAD

**Issue by vboctor** [OfficeDev/ews-java-api#157]
This issue is to make a decision whether we want to continue using the model where all strings are in define in a Strings class and referenced from there.

The reason behind this design is that in the internal codebase to handle localized strings, we have a tool that define strings in a file that is compiled into C# and then compiled with rest of the code.  Such localization is not a necessity for ews-java-api since strings are not localized.

**Comment by evpaassen** [comment]
I don't see why we would ever need String localization is this library. If we would, however, this class is not really gonna help, since it's an abstract class with static strings and not some kind of injected resource bundle.

Perhaps we should check the number of usages of each string. If almost every string would be used just once (I think that's the case with most of them) we could easily just inline them and ditch the class.

**Comment by vboctor** [comment]
+1 - I also think we should inline them, just in case it wasn't clear from my description of the issue :)

**Comment by barisaydinoglu** [comment]
In Strings class there are some fields with multi usage, e.g:
- AutodiscoverCouldNotBeLocated
- AutodiscoverError
- InvalidAsyncResult
- InvalidPropertyValueNotInRange
- MaximumRedirectionHopsExceeded
- ServiceRequestFailed, 
- WLIDCredentialsCannotBeUsedWithLegacyAutodiscover

So, replacing with inline strings is not efficient because of maintanence.

**Comment by serious6** [comment]
I think multi-used strings may be an indicator to provide an own exception class which makes it superfluous. For example the following:
```
AutodiscoverException ---->
                -  AutodiscoverResponseException  
                -  AutodiscoverNotLocatedException                                 
```

**Comment by Nowheresly** [comment]
I just made a PR for this issue.
All strings have been inlined.
I created some specific exceptions for multi-used strings following the hint given by @serious6.
Sometimes, the original exception was final and thus, it was not possible to create a more specific subclass (eg ServiceValidationException).

**Comment by serious6** [comment]
_merged with #246_
