### ISSUE TITLE
Configuration of the maven-bundle-plugin seems to be missing

### ISSUE THREAD

**Issue by evpaassen** [OfficeDev/ews-java-api#174]
The configuration of the `maven-bundle-plugin` in the `pom.xml` seems to be non-existent. This causes errors displayed in IntelliJ IDEA:

```
The package is not exported by the bundle dependencies less... (Ctrl+F1) 

This inspections reports usage of classes from packages not accessible inside the OSGi context - i.e. not imported neither implicitly nor via manifest file. Asking for such a classes may cause "class not found" exceptions at runtime.
The inspection is only effective for modules with OSGi facet set to use existing manifest file.
```

The `maven-bundle-plugin` was added in #98 to fix #97, addding OSGi support. @Arcticwolf, could you have a look at this, perhaps?

See: http://felix.apache.org/site/apache-felix-maven-bundle-plugin-bnd.html

**Comment by vboctor** [comment]
@Arcticwolf will you be able to address this issue shortly?  If not, we can revert the #98 change for now until you get time to address the issue.  Please let us know either way.

**Comment by Arcticwolf** [comment]
@vboctor @evpaassen Hi! I will have a look at it.

**Comment by Arcticwolf** [comment]
@evpaassen Just a few words before I check: it just seems like there is no configuration, but actually if you don't define the Import-Packages and Export-Packages by yourself, the plugin do this automatically for you. This here is created by the plugin just now:

Export-Package: microsoft.exchange.webservices.data;uses:="javax.xml.bin
 d,javax.xml.parsers,javax.xml.stream,javax.xml.validation,org.apache.ht
 tp.conn,org.w3c.dom,org.xml.sax";version="1.3.0.SNAPSHOT"

Import-Package: javax.naming,javax.naming.directory,javax.net.ssl,javax.
 xml.bind,javax.xml.namespace,javax.xml.parsers,javax.xml.stream,javax.x
 ml.stream.events,javax.xml.validation,javax.xml.ws.http,org.apache.comm
 ons.codec.binary;version="[1.6,2)",org.apache.commons.logging;version="
 [1.2,2)",org.apache.http,org.apache.http.auth,org.apache.http.client,or
 g.apache.http.client.config,org.apache.http.client.methods,org.apache.h
 ttp.config,org.apache.http.conn,org.apache.http.conn.socket,org.apache.
 http.conn.ssl,org.apache.http.cookie,org.apache.http.entity,org.apache.
 http.impl.client,org.apache.http.impl.conn,org.apache.http.message,org.
 w3c.dom,org.xml.sax

**Comment by Arcticwolf** [comment]
@evpaassen hmmm ... I don't get that error/warning :( In which situation exactly do you get that warning? Which IntelliJ version do you use? I use IntelliJ 14.0.2 (build 139.659) ... Maybe your maven specific plugin in IntelliJ can't handle the auto-generating of the plugin?

**Comment by evpaassen** [comment]
I have no experience with OSGi (I don't use it), but here's how to reproduce the problem. I'm using the same IntelliJ version as you do: 14.0.2, build 139.659.

I just cloned a fresh version of this repo and I opened the project with IntelliJ. I hit the *Reimport All Maven Projects* button in the *Maven Projects* panel and then *Build* > *Rebuild project*.

When you would then open `ExchangeServiceBase.java`, you would notice all usages of classes from the `org.apache.http` package to be underlined in red (see import statements of this class, for example) with the aforementioned error.

**Comment by evpaassen** [comment]
@Arcticwolf Did you already manage to reproduce the issue?

**Comment by Arcticwolf** [comment]
@evpaassen yes, sry that I don't have answered so far. Ok now I get the warnings too ... it is a little bit strange, since we don't plan to export the org.apache.http package. I will have a look how to fix that. nevertheless the project works in an osgi environment, since i have tested it in one, so I assume that the auto generation of the plugin just add too much to the export-package part

**Comment by Arcticwolf** [comment]
ah ok ... now i see ... that made no problems since i exported these dependencies from a different bundle and so the dependies were available at runtime for me. let me check

**Comment by Arcticwolf** [comment]
ok ... i've created a pull request where this issue is fixed. However, the pull request should be tested before the merge, since I'm not 100% sure if the libs are behaving like the ones used before. And unfortunately I have currently not enough time to test this in a good manner.

Kind regards,
Felix

**Comment by vboctor** [comment]
The OSGI change is now reverted as per discussion on PR #177

**Comment by aertoria** [comment]
+1

Recently I encounter a issue maybe related to this. When project imported, there is a issue regarding not being able to find a maven dependency within ./m2 location. However, there is a .jar there. The problem is that Intellij insist to look for .bundle file rather than .jar file. Any solution for that?


Library Maven: org.apache.directory.jdbm:apacheds-jdbm1:bundle:2.0.0-M2 has broken classes path:   /Users/ethan.wang/.m2/repository/org/apache/directory/jdbm/apacheds-jdbm1/2.0.0-M2/apacheds-jdbm1-2.0.0-M2.bundle
