### ISSUE TITLE
Question - single instance (Singleton object) of ExchangeService 

### ISSUE THREAD

**Issue by aquav** [OfficeDev/ews-java-api#252]
We are using ews-java-api version 1.2 and invoking it via a quartz scheduler every 5 seconds. We don’t allow multiple threads of quartz job (using @DisallowConcurrentExecution).
We create a new instance of ExchangeService object to build the service and using SearchFilter to find items on Exchange Server. We are using basic authentication.

            ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2010_SP2);
            WebCredentials credentials = getExchangeCredentials();
            service.setCredentials(credentials);
            service.setTraceEnabled(logger.isTraceEnabled());
            service.setTraceListener(this);

            SearchFilter.SearchFilterCollection searchFilterCollection =
                    new SearchFilter.SearchFilterCollection(LogicalOperator.And);
            searchFilterCollection.add(new SearchFilter.IsEqualTo(EmailMessageSchema.IsRead, "false"));
            return service.findItems(new FolderId(WellKnownFolderName.Inbox, new Mailbox(emailAddress)), searchFilterCollection, view);

When we ran the application on tomcat (v 7.0.57) and unix (LINUX 6.5). Open File Descriptors counts increasing at the rate of ~1000 / day. We took count using ‘lsof’ command.
We are seeing lot of “can’t identify protocol” and this is causing OS to crash as we have limit of 10k open file descriptor limit. 
When we profiled the application, we saw sockets were opening and closing continuously. In 6 hour run we observed 3k sockets were open and closed. This is probably we are creating and doing search for every 5 seconds but I assumed that socket connection pools are managed internally and would use limited number of sockets.

Also we observed that sockets were closed by Finalizer thread rather than any method call of HttpClient. 

We need help to find the answers of following questions:-
1.	Are ews-java-api v1.2 or v1.3 are thread safe and can be run via a scheduler/Quartz job? 
2.	Will it be ok if we create a single instance (Singleton object) of ExchangeService (microsoft.exchange.webservices.data.ExchangeService) and use it for every request?
3.	Is there is way to manage the socket connections via a configurations?

**Comment by jglynn** [comment]
+1

**Comment by evpaassen** [comment]
*I don't have any experience with quartz, but I'll try to provide you a generic answer.*

I see you're using version 1.2 of the library. This version is know to be very leaky, so you might want to give a recent snapshot a try. It's not like the previous 'stable' versions were anywhere near stable anyway. Now let me answer some of your questions.

The `ExchangeService` is absolutely NOT tread-safe, so you'll have create an instance per thread. It's recommended to re-use `ExchangeService` instances across multiple requests when possible, however. This enables HTTP keep-alive, makes authentication more efficient because the auth cache is kept and also preserves load-balancing cookies.

Currently, it's up to you how you manage these instances. This could be hard in a multi-threaded scenario. In my case, I created a pool using an `ArrayBlockingQueue` (see [this stackoverflow post](http://stackoverflow.com/questions/1137118/does-this-basic-java-object-pool-work/1139830#1139830
)) to manage them. On application startup, the pool is populated with *n* `ExchangeService` instances. Before a making a request, a service instance is obtained from the pool and after the request, the instance is returned (within a `finally` block to prevent leaking the service instance in case of exceptions).

When the `ExchangeService` is disposed, make sure to call the `close()` method to release the connection properly.

> Is there is way to manage the socket connections via a configurations?

No, just create as many `ExchangeService` instances as you need. Every instance will use one connection.

**Comment by aquav** [comment]
Thanks a lot Erik for responding. Yes, we can try managing instances of exchange service object.
However I don't see any specific close method on ExchangeService class of v 1.2. The only close method I see is of HttpClientWebRequest class and it is called in SimpleServiceRequestBase.java in finally block.
This method is releasing the connection which is used to read the response!

**Comment by evpaassen** [comment]
> Yes, we can try managing instances of exchange service object. However I don't see any specific close method on ExchangeService class of v1.2.

That's correct. The 1.2 release is leaking connections everywhere. I should say, that version is totally unusable.

I fixed this some time ago and the `ExchangeServiceBase` (superclass of `ExchangeService`) now implements `Closeable`, so I'd strongly suggest using a more recent snapshot.

**Comment by aquav** [comment]
Thanks Erik!

**Comment by serious6** [comment]
@aquav please have in mind that using a snapshot version (if you are planning to do that) means that this version is under development. I therefore strongly suggest in storing a specific snapshot version in a local repo and only update if you also can handle possible violations. This for example can happen if classes are moved or if dependencies are changed. Maybe [this could be interesting](http://mojo.codehaus.org/versions-maven-plugin/examples/lock-snapshots.html) for you

**Comment by aquav** [comment]
@serious6 yes, I fully understand. Thanks for the information.
