### ISSUE TITLE
Requesting for stable ews-java-api release 

### ISSUE THREAD

**Issue by nshowkath** [OfficeDev/ews-java-api#320]
Hi ,

Posted new thread as previous (same) threads were closed . 
Sorry for asking same question again .
We are requesting for one stable ews-java-api release .Could you let me know when you are planning for stable release , it helps us if in case to not use not use SNAPSHOT version one that has not been released.
P.S : I referred below  thread  for ews-java-api published version
https://github.com/OfficeDev/ews-java-api/issues/1
https://oss.sonatype.org/content/repositories/snapshots/com/microsoft/ews-java-api/ews-java-api/
Thanks,
Showkath.

**Comment by serious6** [comment]
@nshowkath thanks for the hints about deploying a stable release. Since discussion on this topic is related to the following issues:
* #288
* #1

For your personal information stable release will be deployed when #39 is resolved and there are no other blocking (or marked for 2.0) issues in the queue.

**Comment by serious6** [comment]
> closing this as duplicate of #317
