### ISSUE TITLE
How to use setStartTimeZone method of Appointment class?

### ISSUE THREAD

**Issue by pranjaljain** [OfficeDev/ews-java-api#357]
Hi All,
Can anyone share the code-snippets of using setStartTimeZone() method of Appointment class.

**Comment by bhagyagdesai** [comment]
Hi All,
We are also not able to set it.. Can anybody help us.

**Comment by itbw** [comment]
Hi @pranjaljain  @bhagyagdesai,

a very simple version of using Time Zone will look like follows: 

```
// first  init connection to server
ExchangeService service = new ExchangeService();
ExchangeCredentials credentials = new WebCredentials(
		"username", "password");

service.setCredentials(credentials);
service.setUrl(new URI("https://hostname/ews/Exchange.asmx"));

// Now we can get TimeZoneDefinitions supported by server
// You can just print time zones first, to see which are available
Collection<TimeZoneDefinition> timeZoneDefinitions = service.getServerTimeZones();

// Select TimeZoneDefinition you need from the collection
// In this example getting time zone by ID
// You can also use name or transition groups and etc.
TimeZoneDefinition timeZoneDefinition = null;
for (TimeZoneDefinition tzd : timeZoneDefinitions) {
	if (tzd.getId().equals("W. Europe Standard Time")) {
		timeZoneDefinition = tzd;
	}
}

// TimeZoneDefinition is now can be set to appointment
Appointment appointment = new Appointment(service);
appointment.setSubject("TimeZoneTest");
appointment.setStart(new Date());
appointment.setStartTimeZone(timeZoneDefinition);
appointment.setEnd(new Date());
appointment.setEndTimeZone(timeZoneDefinition);

appointment.save(WellKnownFolderName.Calendar);
```

However, different versions of Exchange work with time zones in a different way. See following link for more information:
https://msdn.microsoft.com/en-US/library/office/Dn789029%28v=EXCHG.150%29.aspx

**Comment by bhagyagdesai** [comment]
Hi @itbw 
i tried above code only change is Time TimeZone.getDefault().getID()="Asia/Calcutta";
Collection<TimeZoneDefinition> timeZoneDefinitions = service.getServerTimeZones();

		// Select TimeZoneDefinition you need from the collection
		// In this example getting time zone by ID
		// You can also use name or transition groups and etc.
		TimeZoneDefinition timeZoneDefinition = null;
		for (TimeZoneDefinition tzd : timeZoneDefinitions) {
			System.out.println("ID = "+tzd.getId()+" name= "+ tzd.getName());
		    if (tzd.getId().equals("Asia/Calcutta")) {
		           timeZoneDefinition = tzd;
		    }
		}

so i got following exception
microsoft.exchange.webservices.data.ServiceLocalException: The time zone definition is invalid or unsupported.

**Comment by itbw** [comment]
Hi @bhagyagdesai,

* The problem is that Exchange server operates with Microsoft time zone definitions and you try to use Java time zone ID. 

* It also seems, that you use an old SNAPSHOT of ewa-java-api library (which just generated TimeZoneDefinitions with Java time zone IDs). Please make sure you use the latest SNAPSHOT, because service.getServerTimeZones() was recently changed, in order to work correctly with Exchange servers.. 

* So, in order to get right time zone, you will need to change from 
```
 if (tzd.getId().equals("Asia/Calcutta")) {
```
to
```
 if (tzd.getId().equals("India Standard Time")) {	
```

* You can find full list of Microsoft Time Zone Index Values on following page:
https://msdn.microsoft.com/en-us/library/ms912391%28v=winembedded.11%29.aspx

**Comment by bhagyagdesai** [comment]
Hi @itbw 
I tried above with new java EWS API following is the code snippet 
TimeZoneDefinition tf = null;
		for (TimeZoneDefinition tzd : timeZoneDefinitions) {
			System.out.println("ID = "+tzd.getId()+" name= "+ tzd.getName());
			//System.out.println(TimeZone.getDefault().getDisplayName());
			
		    if (tzd.getId().equals("India Standard Time")) {
		    	tf = tzd;
		           break;
		    }
		}
		
	//	System.out.println("Default timezone = "+TimeZone.getDefault().getID();
		
		
		try {
			Appointment appointment = new Appointment(service);
			appointment.setSubject("TimeZoneTest");
			appointment.setStart(new Date());
			appointment.setStartTimeZone(tf);
			appointment.setEnd(new Date());
			appointment.setEndTimeZone(tf);
			 appointment.getRequiredAttendees().add("miriamkenig2@PM-2008-R2.local");
			appointment.save(WellKnownFolderName.Calendar);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

i got following exception

ID = Dateline Standard Time name= (UTC-12:00) International Date Line West
TZ=Dateline Standard Time
ID = UTC-11 name= (UTC-11:00) Coordinated Universal Time-11
TZ=UTC-11
ID = Samoa Standard Time name= (UTC-11:00) Samoa
TZ=Samoa Standard Time
ID = Hawaiian Standard Time name= (UTC-10:00) Hawaii
TZ=Hawaiian Standard Time
ID = Alaskan Standard Time name= (UTC-09:00) Alaska
TZ=Alaskan Standard Time
ID = Pacific Standard Time (Mexico) name= (UTC-08:00) Baja California
TZ=Pacific Standard Time (Mexico)
ID = Pacific Standard Time name= (UTC-08:00) Pacific Time (US & Canada)
TZ=Pacific Standard Time
ID = US Mountain Standard Time name= (UTC-07:00) Arizona
TZ=US Mountain Standard Time
ID = Mountain Standard Time (Mexico) name= (UTC-07:00) Chihuahua, La Paz, Mazatlan
TZ=Mountain Standard Time (Mexico)
ID = Mountain Standard Time name= (UTC-07:00) Mountain Time (US & Canada)
TZ=Mountain Standard Time
ID = Central America Standard Time name= (UTC-06:00) Central America
TZ=Central America Standard Time
ID = Central Standard Time name= (UTC-06:00) Central Time (US & Canada)
TZ=Central Standard Time
ID = Central Standard Time (Mexico) name= (UTC-06:00) Guadalajara, Mexico City, Monterrey
TZ=Central Standard Time (Mexico)
ID = Canada Central Standard Time name= (UTC-06:00) Saskatchewan
TZ=Canada Central Standard Time
ID = SA Pacific Standard Time name= (UTC-05:00) Bogota, Lima, Quito
TZ=SA Pacific Standard Time
ID = Eastern Standard Time name= (UTC-05:00) Eastern Time (US & Canada)
TZ=Eastern Standard Time
ID = US Eastern Standard Time name= (UTC-05:00) Indiana (East)
TZ=US Eastern Standard Time
ID = Venezuela Standard Time name= (UTC-04:30) Caracas
TZ=Venezuela Standard Time
ID = Paraguay Standard Time name= (UTC-04:00) Asuncion
TZ=Paraguay Standard Time
ID = Atlantic Standard Time name= (UTC-04:00) Atlantic Time (Canada)
TZ=Atlantic Standard Time
ID = Central Brazilian Standard Time name= (UTC-04:00) Cuiaba
TZ=Central Brazilian Standard Time
ID = SA Western Standard Time name= (UTC-04:00) Georgetown, La Paz, Manaus, San Juan
TZ=SA Western Standard Time
ID = Pacific SA Standard Time name= (UTC-04:00) Santiago
TZ=Pacific SA Standard Time
ID = Newfoundland Standard Time name= (UTC-03:30) Newfoundland
TZ=Newfoundland Standard Time
ID = E. South America Standard Time name= (UTC-03:00) Brasilia
TZ=E. South America Standard Time
ID = Argentina Standard Time name= (UTC-03:00) Buenos Aires
TZ=Argentina Standard Time
ID = SA Eastern Standard Time name= (UTC-03:00) Cayenne, Fortaleza
TZ=SA Eastern Standard Time
ID = Greenland Standard Time name= (UTC-03:00) Greenland
TZ=Greenland Standard Time
ID = Montevideo Standard Time name= (UTC-03:00) Montevideo
TZ=Montevideo Standard Time
ID = Bahia Standard Time name= (UTC-03:00) Salvador
TZ=Bahia Standard Time
ID = UTC-02 name= (UTC-02:00) Coordinated Universal Time-02
TZ=UTC-02
ID = Mid-Atlantic Standard Time name= (UTC-02:00) Mid-Atlantic
TZ=Mid-Atlantic Standard Time
ID = Azores Standard Time name= (UTC-01:00) Azores
TZ=Azores Standard Time
ID = Cape Verde Standard Time name= (UTC-01:00) Cape Verde Is.
TZ=Cape Verde Standard Time
ID = Morocco Standard Time name= (UTC) Casablanca
TZ=Morocco Standard Time
ID = UTC name= (UTC) Coordinated Universal Time
TZ=UTC
ID = GMT Standard Time name= (UTC) Dublin, Edinburgh, Lisbon, London
TZ=GMT Standard Time
ID = Greenwich Standard Time name= (UTC) Monrovia, Reykjavik
TZ=Greenwich Standard Time
ID = W. Europe Standard Time name= (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
TZ=W. Europe Standard Time
ID = Central Europe Standard Time name= (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague
TZ=Central Europe Standard Time
ID = Romance Standard Time name= (UTC+01:00) Brussels, Copenhagen, Madrid, Paris
TZ=Romance Standard Time
ID = Central European Standard Time name= (UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb
TZ=Central European Standard Time
ID = W. Central Africa Standard Time name= (UTC+01:00) West Central Africa
TZ=W. Central Africa Standard Time
ID = Namibia Standard Time name= (UTC+01:00) Windhoek
TZ=Namibia Standard Time
ID = Libya Standard Time name= (UTC+02:00) Tripoli
TZ=Libya Standard Time
ID = Jordan Standard Time name= (UTC+02:00) Amman
TZ=Jordan Standard Time
ID = GTB Standard Time name= (UTC+02:00) Athens, Bucharest
TZ=GTB Standard Time
ID = Middle East Standard Time name= (UTC+02:00) Beirut
TZ=Middle East Standard Time
ID = Egypt Standard Time name= (UTC+02:00) Cairo
TZ=Egypt Standard Time
ID = Syria Standard Time name= (UTC+02:00) Damascus
TZ=Syria Standard Time
ID = South Africa Standard Time name= (UTC+02:00) Harare, Pretoria
TZ=South Africa Standard Time
ID = FLE Standard Time name= (UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius
TZ=FLE Standard Time
ID = Turkey Standard Time name= (UTC+02:00) Istanbul
TZ=Turkey Standard Time
ID = Israel Standard Time name= (UTC+02:00) Jerusalem
TZ=Israel Standard Time
ID = E. Europe Standard Time name= (UTC+02:00) Minsk
TZ=E. Europe Standard Time
ID = Kaliningrad Standard Time name= (UTC+03:00) Kaliningrad
TZ=Kaliningrad Standard Time
ID = Arabic Standard Time name= (UTC+03:00) Baghdad
TZ=Arabic Standard Time
ID = Arab Standard Time name= (UTC+03:00) Kuwait, Riyadh
TZ=Arab Standard Time
ID = E. Africa Standard Time name= (UTC+03:00) Nairobi
TZ=E. Africa Standard Time
ID = Russian Standard Time name= (UTC+04:00) Moscow, St. Petersburg, Volgograd
TZ=Russian Standard Time
ID = Iran Standard Time name= (UTC+03:30) Tehran
TZ=Iran Standard Time
ID = Arabian Standard Time name= (UTC+04:00) Abu Dhabi, Muscat
TZ=Arabian Standard Time
ID = Azerbaijan Standard Time name= (UTC+04:00) Baku
TZ=Azerbaijan Standard Time
ID = Mauritius Standard Time name= (UTC+04:00) Port Louis
TZ=Mauritius Standard Time
ID = Georgian Standard Time name= (UTC+04:00) Tbilisi
TZ=Georgian Standard Time
ID = Caucasus Standard Time name= (UTC+04:00) Yerevan
TZ=Caucasus Standard Time
ID = Afghanistan Standard Time name= (UTC+04:30) Kabul
TZ=Afghanistan Standard Time
ID = Pakistan Standard Time name= (UTC+05:00) Islamabad, Karachi
TZ=Pakistan Standard Time
ID = West Asia Standard Time name= (UTC+05:00) Tashkent
TZ=West Asia Standard Time
ID = Ekaterinburg Standard Time name= (UTC+06:00) Ekaterinburg
TZ=Ekaterinburg Standard Time
ID = India Standard Time name= (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi
TZ=India Standard Time
microsoft.exchange.webservices.data.core.exception.service.remote.ServiceRequestException: The request failed. An internal server error occurred. The operation failed.
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:74)
	at microsoft.exchange.webservices.data.core.request.MultiResponseServiceRequest.execute(MultiResponseServiceRequest.java:158)
	at microsoft.exchange.webservices.data.core.ExchangeService.internalCreateItems(ExchangeService.java:598)
	at microsoft.exchange.webservices.data.core.ExchangeService.createItem(ExchangeService.java:657)
	at microsoft.exchange.webservices.data.core.service.item.Item.internalCreate(Item.java:245)
	at microsoft.exchange.webservices.data.core.service.item.Item.save(Item.java:373)
	at testcalender.main(testcalender.java:88)
Caused by: microsoft.exchange.webservices.data.core.exception.service.remote.ServiceResponseException: An internal server error occurred. The operation failed.
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.processWebException(ServiceRequestBase.java:548)
	at microsoft.exchange.webservices.data.core.request.ServiceRequestBase.validateAndEmitRequest(ServiceRequestBase.java:641)
	at microsoft.exchange.webservices.data.core.request.SimpleServiceRequestBase.internalExecute(SimpleServiceRequestBase.java:62)
	... 6 more

**Comment by itbw** [comment]
Hi @bhagyagdesai,

* I have the same error as you. I'm afraid, it might be a bug in creating Bias value in Period tag.

* This is the request, which client sends to server:
```
<t:StartTimeZone Name="(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi" Id="India Standard Time">
<t:Periods>
  <t:Period Bias="-P5DT130H39M48.0S" Name="Standard" Id="trule:Microsoft/Registry/India Standard Time/1-Standard" />
</t:Periods>
<t:TransitionsGroups>
  <t:TransitionsGroup Id="0">
	<t:Transition>
	  <t:To Kind="Period">trule:Microsoft/Registry/India Standard Time/1-Standard</t:To>
	</t:Transition>
  </t:TransitionsGroup>
</t:TransitionsGroups>
<t:Transitions>
  <t:Transition>
	<t:To Kind="Group">0</t:To>
  </t:Transition>
</t:Transitions>
</t:StartTimeZone>
```

* Correct value for Bias should be:
```
<t:Period Bias="-PT5H30M" Name="Standard" Id="trule:Microsoft/Registry/India Standard Time/1-Standard" />
```

**Comment by serious6** [comment]
@itbw will you provide a Pull request for this issue? As you already did some great work on investigating this issue.

**Comment by serious6** [comment]
Possible ref. to #396 for the use of TimeWindow.

**Comment by itbw** [comment]
@serious6 I will have a closer look and prepare a pull request.

**Comment by itbw** [comment]
Hi @serious6, I created a pull request. I'm not sure about using Joda Time instead of old Java parsing, so I didn't make a precise description. Please have a look at PR, so I can modify it, if necessary.

**Comment by softashu** [comment]
the issue mainly due to 

this.periods.size() <=0 and  this.transitions.size() = 0

see the following validation code.


	/**
	 * Validates this time zone definition.
	 * 
	 * @throws ServiceLocalException
	 *             the service local exception
	 */
	public void validate() throws ServiceLocalException {
		// The definition must have at least one period, one transition group
		// and one transition,
		// and there must be as many transitions as there are transition groups.
		if (this.periods.size() < 1 || this.transitions.size() < 1
				|| this.transitionGroups.size() < 1
				|| this.transitionGroups.size() != this.transitions.size()) {
			throw new ServiceLocalException(
					Strings.InvalidOrUnsupportedTimeZoneDefinition);
		}


How could  be resolve?

Thanks
