### ISSUE TITLE
Set StartTimeZone  and EndTimeZone on an appointment

### ISSUE THREAD

**Issue by FVDEV** [OfficeDev/ews-java-api#360]
Hi,
I want to set the StartTimeZone and the EndTimeZone on an appointment.
With the old EWS Java API 1.2, it will be not possible.
Have you had problems with the new API version?
Thank you

**Comment by buddha1990** [comment]
We are using EWS 2.0 SNAPSHOT, we are facing issue while setting Start and End time zone. 
Our code looks like: 
 TimeZoneDefinition st = new TimeZoneDefinition() {
					{
						setId("Etc/GMT+10");
						// or by Name as : setName("GMT-12:00");
					}
				};

This is giving "InvalidOrUnsupportedTimeZoneDefinitionException".
We are unable to find any valid values for Id or Name. Please let us know the correct approach with some sample code.

**Comment by itbw** [comment]
Hi @buddha1990, you can have a look at my answer in #357.

**Comment by jeremydstanton** [comment]
I don't understand how the code in the link you provided is an answer to this problem if it too has the same problem.  Am I missing something?

**Comment by itbw** [comment]
Hi @jeremydstanton,

* InvalidOrUnsupportedTimeZoneDefinitionException indicates about two possible problems:

* First, Invalid TimeZoneDefinition. 
 * Before writing time zone to Exchange server,  ews-java-api library does a validation of time zone definition. 
 * In two words: TimeZone definition should contain information about Periods and Transitions. So, if you just create an instance of TimeZoneDefinition with ID, it will not pass the validation. 

* Second, UnsupportedTimeZoneDefinition
 * Exchange server operates with Microsoft time zone definitions and the code above tries to use Java time zone ID, which is not supported by server.
 *  You can find full list of Microsoft Time Zone Index Values on following page: https://msdn.microsoft.com/en-us/library/ms912391%28v=winembedded.11%29.aspx

* To the question, how is my answer is related:
 * The code provided above will not work, because TimeZone Definition will not pass the validation, and will not be accepted by server.
 * The correct way will be to use  ``` service.getServerTimeZones() ```, and then pick one you need.

* To the question of Exchange2007_SP1.
 * According to https://msdn.microsoft.com/en-US/library/office/Dn789029%28v=EXCHG.150%29.aspx, Exchange2007_SP1 does not support StartTimeZone and EndTimeZone, but a MeetingTimeZone.
 * In this case, you should get time zones with ``` service.getServerTimeZones() ``` and then specify only StartTimeZone (not EndTimeZone). ews-java-api library will change StartTimeZone to MeetingTimeZone automatically. 

*  Please make sure you use the latest SNAPSHOT, because service.getServerTimeZones() was recently changed, in order to work correctly with Exchange servers.

**Comment by jeremydstanton** [comment]
Thanks for your prompt reply.  I pulled down your latest SNAPSHOT, recompiled and ran the code your link provided and am now getting this error "The service request GetServerTimeZones is only valid for Exchange version Exchange2010 or later."  So you're telling me that I need to use getServerTimeZones() to get the one I need but that's not valid for the server version I'm implementing this for.... So I am still in a position where I cannot create events in Exchange2007_SP1.

**Comment by jeremydstanton** [comment]
Could my problem be that I'm using the snapshots from oss-sonatype and I need to instead pull the code directly from github?

**Comment by itbw** [comment]
@jeremydstanton 

* Yes, you absolutely right, getServerTimeZones() work only for 2010+ version. The problem is, however, in the current implementation of ews-java-api. 

* Initially it was implemented to validate TimeZoneDefinition for correct Periods and Transitions, which is not necessary, if you use Exchange2007_SP1:
https://github.com/OfficeDev/ews-java-api/blob/master/src/main/java/microsoft/exchange/webservices/data/property/complex/time/TimeZoneDefinition.java#L335

* Theoretically for Exchange 2007 SP1 your code should look like follows:
```
// init connection
ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2007_SP1);
ExchangeCredentials credentials = new WebCredentials();

service.setCredentials(credentials);
service.setUrl(new URI("https://hostname/ews/Exchange.asmx"));

// Create new TimeZoneDefinition by using MS Time Zone ID
TimeZoneDefinition timeZoneDefinition = new TimeZoneDefinition();
timeZoneDefinition.setId("W. Europe Standard Time");

// Setting TimeZoneDefinition to appointment
Appointment appointment = new Appointment(service);
appointment.setSubject("TimeZoneTest");
appointment.setStart(new Date());
// setStartTimeZone will be automatically transformed into MeetingTimeZone
appointment.setStartTimeZone(timeZoneDefinition);
appointment.setEnd(new Date());

appointment.save(WellKnownFolderName.Calendar);
```

* Code where StartTimeZone will be replaced by MeetingTimeZone 
https://github.com/OfficeDev/ews-java-api/blob/master/src/main/java/microsoft/exchange/webservices/data/property/definition/StartTimeZonePropertyDefinition.java#L88

* However, because of validation of TimeZoneDefinition, example above will not work. So its can be three ways to fix problem:
 * Notify core developers to fix validation problem
 * Get proper TZD from 2010+ server
 * Clone library and comment out validation code.

**Comment by jeremydstanton** [comment]
Shouldn't this issue still be open since the code doesnt currently work?  I mean technically the issue in the original request was fixed but it's simply been replaced with a different blocker.  Is the proper procedure to open another issue with this new blocker?

**Comment by serious6** [comment]
#357 has been reopened as first occurrence

**Comment by itbw** [comment]
@serious6 I suggest to change validation method in TimeZoneDefinition. Currently,

**Comment by jhoeflaken** [comment]
Just to let you know I resolved this by extending the TimeZoneDefinition class and overriding the validate method making sure the inherited/super validate method isn't called. I than use the Microsoft timezone id as suggested earlier and it works fine against 2007SP1. I just named it TimeZoneDefinition2007. No need to compile yourself.

Kind regards,

Jacob

**Comment by jeremydstanton** [comment]
I solved the problem without any code changes by querying the microsoft
endpoint for office365, fetching the timezone list that way, pulling out
the one I want, and using that. It's not a self contained solution but it
works well.

**Comment by jhoeflaken** [comment]
@jeremydstanton That is certainly a smart solution too. Thanks for sharing.
