### ISSUE TITLE
ews release 2.1 planning

### ISSUE THREAD

**Issue by serious6** [OfficeDev/ews-java-api#666]
Ref. #665  For a possible 2.1 release I see the following features at the skyline:

- relevant bug-fixes

Please vote on issus by placing your +1 or linking them to this ticket while providing a justification why it is important to you and others. This release can include all changes that will not break the actual api.

**Comment by serious6** [comment]
_Created to further outline this_ [call for action](https://github.com/OfficeDev/ews-java-api/issues/661#issuecomment-404829212)

**Comment by benariss** [comment]
A fix for #353 would be very much appreciated.  It's been present since at least Exchange 2007 (https://blogs.msdn.microsoft.com/mstehle/2009/02/12/kb-xml-schema-validation-errors-when-exchange-web-service-requests-and-responses-have-invalid-xml-characters/) so it's doubtful that MS will ever fix it, so it's imperative that the XML validation done by this library is able to handle the errant unicode characters which may be present in the data received from EWS.  
There is a WIP PR for this issue (#409) but it includes an additional dependency which may need additional work to be factored out.

**Comment by serious6** [comment]
closed as of latest comment on #661
